apiVersion: v1
kind: Service
metadata:
  name: app-{{ .Release.Name }}-pod-service
  labels:
    env: dev
    owner: Teranteks

spec:
  selector:
    project: k8s-app-{{ .Release.Name }}
  ports:
    - name: k8s-app-listener-{{ .Release.Name }}
      protocol: TCP
      port: {{ .Values.svc_port }}
      targetPort: {{ .Values.svc_target_port }}
  type: LoadBalancer